loggingLevel: ALL
placement-tracking:
- STONE
- ENDER_STONE
- GRANITE
- ANDESITE
- DIORITE
- OBSIDIAN
- NETHERRACK
- SOUL_SAND
- SAND
- RED_SAND
- GRAVEL
- SANDSTONE
- RED_SANDSTONE
- CLAY
- GRASS_BLOCK
- PODZOL
- DIRT
- HARDENED_CLAY
- STAINED_CLAY
- OAK_WOOD
- BIRCH_WOOD
- SPRUCE_WOOD
- JUNGLE_WOOD
- DARK_OAK_WOOD
- ACACIA_WOOD
- OAK_LOG
- BIRCH_LOG
- SPRUCE_LOG
- JUNGLE_LOG
- DARK_OAK_LOG
- ACACIA_LOG
- GLOWSTONE
- COAL_ORE
- IRON_ORE
- GOLD_ORE
- REDSTONE_ORE
- LAPIS_ORE
- QUARTZ_ORE
- DIAMOND_ORE
drop-consumables: true